# Setup
highlighter:      Rouge

title: Julia Rozanova
tagline: Again
url: https://juliarozanova.github.io
baseurl: /
permalink: pretty
paginate: 3
paginate_path: "blog/page:num"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

collections:
  - sections
  - bibfirst
  - bibetal
  - dissertations

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Julia Rozanova
  url: https://twitter.com/juliaroz
  email: juliarozanova@gmail.com

# Custom vars
version: 3.0.0

github:
  repo:           https://github.com/juliarozanova/juliarozanova.github.io.git